language: ruby
rvm:
  - 1.8.7
  - 1.9.2
gemfile:
  - gemfiles/2.3.gemfile
  - gemfiles/3.0.gemfile
  - gemfiles/3.1.gemfile
  - gemfiles/3.2.gemfile
before_script: "bundle install && bundle exec rake appraisal:install"
script: "bundle exec rake clean test"
